### ISSUE TITLE
Maybe a little miss in your code

### ISSUE THREAD

**Issue by mililic85** [alpharithms/indicators#4]
Hi @alphazwest, I loved your post 

https://www.alpharithms.com/relative-strength-index-rsi-in-python-470209/#:~:text=Use%20the%20RS%20value%20to,both%20the%20gains%20and%20losses)

thanks very much.

Just find a possible bug (VS code noticed me), I think where it says:

`difference = do_round(wilder_data[i] - wilder_data[i - 1])`

inside the method, should say:

`difference = do_round(data[i] - data[i - 1])`

kind regards!

**Comment by alphazwest** [comment]
Thanks for the catch! I updated the code here -- looks like I had it right in the article somehow...
